from pathlib import Path
from typing import Any

DEFAULT_DATA_DIR = Path(__file__).parent.parent.parent / "data"
DEFAULT_DUST_CONSTANTS_PATH = DEFAULT_DATA_DIR / "dust_constants.txt"


def save_dust_constants(constants: dict[str, Any], path: str | Path = DEFAULT_DUST_CONSTANTS_PATH) -> None:
    """Save pre-computed dust opacity constants to a text file.

    Parameters
    ----------
    constants : dict
        Dictionary mapping constant names to float values.
        Expected keys (all opacities in cm^2/g):
        kUV_drn, kUV_drn_abs, kv_drn, kIR_drn, omega_1500_drn, g_1500_drn,
        kUV_hir, kUV_hir_abs, kv_hir, kIR_hir, omega_1500_hir, g_1500_hir.
    path : str or Path
        Output file path. Defaults to data/dust_constants.txt.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("# Dust opacity and scattering constants at key wavelengths\n")
        f.write("# Computed from grain size distributions — do not edit by hand\n")
        for key, val in constants.items():
            f.write(f"{key:<20} {val:.8f}\n")


def load_dust_constants(path: str | Path = DEFAULT_DUST_CONSTANTS_PATH) -> dict[str, float]:
    """Load pre-computed dust opacity constants from a text file.

    Parameters
    ----------
    path : str or Path
        Path to the dust constants file (generated by save_dust_constants).
        Defaults to data/dust_constants.txt.

    Returns
    -------
    dict
        Dictionary mapping constant names to float values.

    Raises
    ------
    FileNotFoundError
        If the constants file does not exist. Run the grain size distribution
        section of the notebook first to generate it.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Dust constants file not found: {path}\n"
            "Run the grain size distribution section of the notebook to generate it."
        )
    consts: dict[str, float] = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            key, val = line.split()
            consts[key] = float(val)
    return consts
